*CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
*CCCC                 Edwards Part                            CCCC
*CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

set mapEdwardCounty(layer, county)  map aquifer places to counties in terms of determining pumping head
   /j17head.   (Medina, Bexar,  Atascosa  ,   Hays,  Comal, Guadalupe)
    j27head.  (Uvalde, KINNEY)/
   MapEdwardsRecharge(layer, county)    map edwards aquifer layer iwht recharge zone counties
/
j17head.   ( "Atascosa" , "Bandera" ,  "Bexar"  ,"Blanco",  "Comal",
                 "Gillespie","Kendall"  , "Kerr" ,  "Medina"  )
j27head.  ("Edwards", "Real" ,"Uvalde", "Kinney") /;

* data is generated by G:\My Drive\EDSIMR\GAM\Edwards\SIR.2015.5081 (1)\SIR.2015.5081\3-Input\Regression R code
* elavation~intercept+j17headelevation_lag+ j27 elev lag + recharge + pump
Table EdwardsRegPar(layer, Regitems)   Edwards Regression Coefficients

           Intercept      J17Head_lag   j27head_lag    Recharge     j27headUse   J17HeadUse
J17Head    4.380e+02      1.359e-01     1.756e-01     5.276e-05            0      -1.596e-04
j27head    3.813e+02      2.345e-01     3.538e-01     1.261e-04     -3.102e-04         0

;

Parameter DEM(aquifer,layer) Land Surface Elevation of well place in Edwards Aquifer
         /  edwards.j17head    738
            edwards.j27head    910/
LiftDiff (layer, county)     the lift differenc for Edwards Aquifer
   /j17head.  Medina     45.67
    j17head.  Bexar      -86.81
    j17head.  Atascosa   -135.88
    j17head.  Hays       15.38
    j17head.  Comal      -16.7
    j17head.  Guadalupe  -121.36
    j27head.  Uvalde     22.87
    j27head.  KINNEY      60.29      /


RechAdj(layer)        the recharge adjustment for Edwards Aquifer
         /
       J17head 0.4
       J27head 0.5/

EdIniLife(layer)     the initial lift distance of Edwards aquifer
         /
       J17head 85
       J27head 58/

;

parameter EdwardMAxLift(Aquifer, layer, county) satisfy the min requirement of Stage V (will be removed after add water market into model)/
   Edwards.j17head. none   206
   Edwards.j27head. none   165  /
;
*CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
*CCCC                 Springs Part                            CCCC
*CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC


Table SpringReg(Springs, Regitems)  springflow regression coeficients  comal(05) and San Macros(75)
                Intercept    J17head        J17Head_lag     Recharge      J17HeadUse
CP05_GuadSA    -5.586e+05   3.265e+02       8.710e+02      6.989e-02      -1.968e-01
CP75_GuadSA    -2.860e+05   1.919e+02       3.636e+02      8.273e-02      -6.975e-02   ;

Table SpringSeasonal(springs, month)   spring flow monthly share (data source: EAA)
               Jan             Feb             Mar           Apr             May            Jun            Jul            Aug            Sep           Oct           Nov             Dec
CP05_GuadSA  0.08744        0.08794        0.08731        0.08601        0.08498        0.08268        0.07970        0.07549        0.07718        0.08103        0.08388        0.08636
CP75_GuadSA  0.08203        0.08337        0.08379        0.08355        0.08664        0.09141        0.08820        0.08128        0.07770        0.07693        0.08157        0.08353
;
parameter springmin(springs)  minimal requirement of spring flows from EAA  cubic feet per second
/
CP05_GuadSA 225
CP75_GuadSA 96
/;

springmin(springs) = springmin(springs) *60.37;
